# Generated by Django 3.0.2 on 2020-01-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
